### ISSUE TITLE
Get an exception with the example:

### ISSUE THREAD

**Issue by nowox** [wbond/pybars3#15]
Just got pybars from `pip install pybars` and `pip install pybars3`

```
#!/usr/bin/python

# Get a compiler
from pybars import Compiler
compiler = Compiler()

# Compile the template
source = u"{{>header}}{{#list people}}{{firstName}} {{lastName}}{{/list}}"
template = compiler.compile(source)

# Add any special helpers
def _list(this, options, items):
    result = [u'<ul>']
    for thing in items:
        result.append(u'<li>')
        result.extend(options['fn'](thing))
        result.append(u'</li>')
    result.append(u'</ul>')
    return result
helpers = {'list': _list}

# Add partials
header = compiler.compile('<h1>People</h1>')
partials = {'header': header}

# Render the template
output = template({
    'people': [
        {'firstName': "Yehuda", 'lastName': "Katz"},
        {'firstName': "Carl", 'lastName': "Lerche"},
        {'firstName': "Alan", 'lastName': "Johnson"}
    ]}, helpers=helpers, partials=partials)

print(output)
```

```
Traceback (most recent call last):
  File "./pyt.py", line 23, in <module>
    header = compiler.compile('<h1>People</h1>')
  File "/usr/lib/python2.7/site-packages/pybars/_compiler.py", line 458, in compile
    assert isinstance(source, unicode)
AssertionError
```

**Comment by mjumbewu** [comment]
Hi @nowox, the issue above is that pybars is expecting a `unicode` value as a template, where you are passing in a `str` value (`'<h1>People</h1>'`). In Python 3 your code would work just fine, but in Python 2 it doesn't. I'd recommend adding `from __future__ import unicode_literals` to the top of your script.

**Comment by wbond** [comment]
@mjumbewu I think the point was that this example is taken from the readme. We just need to fix it there.

**Comment by mjumbewu** [comment]
ah, i see.
