### ISSUE TITLE
Test failing: test_invalid_python_identifiers_cannot_be_used_as_keyword_arguments

### ISSUE THREAD

**Issue by mozboz** [wbond/pybars3#22]
Python 2.7.8

```
$ python tests.py
.........................................................................E........................................................
======================================================================
ERROR: test_invalid_python_identifiers_cannot_be_used_as_keyword_arguments (tests.test_acceptance.TestAcceptance)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/james/dev/first-contact/pagegen/pybars3/tests/test_acceptance.py", line 2041, in test_invalid_python_identifiers_cannot_be_used_as_keyword_arguments
    self.assertRender(template, context, result)
  File "/home/james/dev/first-contact/pagegen/pybars3/tests/test_acceptance.py", line 47, in assertRender
    self.assertEqual(result, render(template, context, helpers=helpers, partials=partials, **kwargs))
  File "/home/james/dev/first-contact/pagegen/pybars3/tests/test__compiler.py", line 32, in render
    template = compiler.compile(source)
  File "/home/james/dev/first-contact/pagegen/pybars3/pybars/_compiler.py", line 780, in compile
    container = self._generate_code(source)
  File "/home/james/dev/first-contact/pagegen/pybars3/pybars/_compiler.py", line 749, in _generate_code
    raise PybarsError("Error at character %s of line %s - %s" % (char_num, line_num, message))
PybarsError: Error at character 7 of line 1 - expected "None"
```

**Comment by isaacdd** [comment]
Does not happen anymore. Closing but feel free to re-open if you still see it happen.
