### ISSUE TITLE
Can't install with python 3.6

### ISSUE THREAD

**Issue by dagnelies** [wbond/pybars3#44]
```
> pip install pybars
Collecting pybars
  Downloading pybars-0.0.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "...\pybars\setup.py", line 22, in <module>
        description = file(
    NameError: name 'file' is not defined

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in ...\pybar
```

**Comment by erichurkman** [comment]
`pip install pybars3` not `pip install pybars`
